name = "lusoi-gardens"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-11-25"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
routes = [
  { pattern = "lusoigardens.com/*", zone_id = "546177b78b4ad09709421913cbded606" }
]
